baseURL = 'https://mysite-ci3.pages.dev/'
draft = false
languageCode = 'ru-ru'
title = 'Sergey Ryazanov'
theme = 'stack'

[params]
    mainSections = ["posts"]
    
    [params.sidebar]
        subtitle = "My life"
        avatar = { enabled = true, local = false, src = "/img/logo.png" }
        favicon = "/img/logo.png"

    [params.widgets]
        homepage = [
            { type = "search" },
            { type = "remark42-last-comments" },
            { type = "archives", params = { limit = 5 } },
            { type = "categories", params = { limit = 10 } },
            { type = "tag-cloud", params = { limit = 10 } }
        ]
        page = [
            { type = "toc" }
        ]

    [params.comments]
        enabled = true
        provider = "remark42"
    
        [params.comments.remark42]
            host = "https://remark42.iamqq.mywire.org"
            site = "mysite-ci3"
            locale = "ru"
            components = ["embed", "last-comments"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Главная"
        url = "/"
        weight = -100
        params = { icon = "home" }

    [[menu.main]]
        identifier = "archives"
        name = "Архив"
        url = "/archives/"
        weight = -90
        params = { icon = "archives" }

    [[menu.main]]
        identifier = "search"
        name = "Поиск"
        url = "/search/"
        weight = -80
        params = { icon = "search" }

    [[menu.main]]
        identifier = "visited-places"
        name = "Посещенные места"
        url = "/visited-places/"
        weight = -70
        params = { icon = "map" }


      